apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-sa
  namespace: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-sa-binding
subjects:
  - kind: ServiceAccount
    name: vault-sa
    namespace: vault
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Secret
metadata:
  name: vault-sa-token
  namespace: vault
  annotations:
    kubernetes.io/service-account.name: "vault-sa"
type: kubernetes.io/service-account-token