apiVersion: v1
kind: Pod
metadata:
  name: test-vault-pod
  namespace: app
spec:
  serviceAccountName: demo-static-app
  containers:
  - name: test-app
    image: nginx:latest
    volumeMounts:
    - name: secrets-store
      mountPath: /mnt/secrets
      readOnly: true
  volumes:
  - name: secrets-store
    secret:
      secretName: secretkv